### ISSUE TITLE
Custom URL Support

### ISSUE THREAD

**Issue by Huskydog9988** [trietmn/go-wiki#2]
Would you consider adding the ability to set a url different from the one [baked in](https://github.com/trietmn/go-wiki/blob/main/utils/utils.go#L77)?

**Comment by trietmn** [comment]
Sorry for the late response, sure why not! I updated a function to change the default Wikipedia URL. Don't know if all of the wrapper is gonna work but happy to help

**Comment by Huskydog9988** [comment]
Alls good, thanks for the update!
